name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build de l'image Docker
      - name: Build Docker Image
        run: docker build -t <supercraft84>/voting-app:latest .

      # Analyse avec Docker Scout
      - name: Run Docker Scout
        run: docker scout <supercraft84>/voting-app:latest

      # Push de l'image sur Docker Hub
      - name: Push Docker Image
        run: docker push <supercraft84>/voting-app:latest